# 是否启用聊天替换功能
enable: true
# 当插件发生冲突时 (聊天栏参数补全出问题) 请调整优先级，无论如何，优先级不可在聊天插件之后
# 事件监听器优先级，以下排序为，越先执行的在越前面
# LOWEST -> LOW -> NORMAL -> HIGH -> HIGHEST
# 不可使用 MONITOR 优先级，使用该优先级会重置回 LOW
priority: LOW

# 权限列表:
# sweet.miao.chat -- 拥有该权限的玩家发送聊天时将被替换成猫娘格式
# sweet.miao.bypass -- 拥有该权限的玩家，即使有以上权限，也不会被替换聊天
