name: SweetMiao
version: '${version}'
main: top.mrxiaom.miao.SweetMiao
api-version: 1.13
depend: [  ]
softdepend: [ PlaceholderAPI ]
authors: [ MrXiaoM ]
commands:
  sweetmiao:
    description: 'The main command of SweetMiao'
    aliases: [ smiao, miao ]
