name: SweetMiao
version: '${version}'
main: top.mrxiaom.miao.SweetMiao
api-version: 1.13
authors: [ MrXiaoM ]
softdepend:
  - CommandPrompter
  - QuickShop
  - TrMenu
folia-supported: true
commands:
  sweetmiao:
    description: 'The main command of SweetMiao'
    aliases: [ smiao, miao ]
